# Etapa de construcción
FROM node:13.12.0-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa final
FROM node:13.12.0-alpine
WORKDIR /app
COPY --from=build /app/package.json ./
COPY --from=build /app/package-lock.json ./
COPY --from=build /app/build ./build
EXPOSE 3000
RUN npm install --only=production
CMD ["npm", "start"]

